### ISSUE TITLE
Don't show crash details

### ISSUE THREAD

**Issue by 1MyNameIsKhan** [farimarwat/ANR-Spy#1] opened 2023-01-02 05:12 UTC
Some ANR when converted to crashes does'nt show details about where this crash has occurred.

Example:

Exception ub.b: [ ++ ANR Spy ++ ]
  at J.N.Mcw1yi1C (N.java)
  at org.chromium.ui.base.EventForwarder.j (EventForwarder.java:339)
  at org.chromium.ui.base.EventForwarder.h (EventForwarder.java:145)
  at Ev.onTouchEvent (Ev.java:40)
  at com.android.webview.chromium.WebViewChromium.onTouchEvent (WebViewChromium.java:35)
  at android.webkit.WebView.onTouchEvent (WebView.java:2637)
  at com.google.android.gms.ads.internal.webview.ac.onTouchEvent (ac.java:9)
  at android.view.View.dispatchTouchEvent (View.java:11891)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3018)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2666)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3024)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2623)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3024)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2623)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3024)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2623)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3024)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2623)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3024)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2623)
  at com.android.internal.policy.DecorView.superDispatchTouchEvent (DecorView.java:449)
  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent (PhoneWindow.java:1837)
  at android.app.Activity.dispatchTouchEvent (Activity.java:3405)
  at com.android.internal.policy.DecorView.dispatchTouchEvent (DecorView.java:411)
  at android.view.View.dispatchPointerEvent (View.java:12135)
  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent (ViewRootImpl.java:5158)
  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:4968)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4494)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4547)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4513)
  at android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:4640)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4521)
  at android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:4697)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4494)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4547)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4513)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4521)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4494)
  at android.view.ViewRootImpl.deliverInputEvent (ViewRootImpl.java:7096)
  at android.view.ViewRootImpl.doProcessInputEvents (ViewRootImpl.java:7070)
  at android.view.ViewRootImpl.enqueueInputEvent (ViewRootImpl.java:7027)
  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent (ViewRootImpl.java:7226)
  at android.view.InputEventReceiver.dispatchInputEvent (InputEventReceiver.java:193)
  at android.os.MessageQueue.nativePollOnce (MessageQueue.java)
  at android.os.MessageQueue.next (MessageQueue.java:366)
  at android.os.Looper.loop (Looper.java:144)
  at android.app.ActivityThread.main (ActivityThread.java:6861)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:450)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:936)

**Comment by farimarwat** [comment] 2023-01-02 05:44
The line (Exception ub.b: [ ++ ANR Spy ++ ]) shows that this ANR has already been converted to crash and ANR spy is working correctly. But the issue is that you want to know the "Blue Clickable Link" in logs window to click on and go directly to that line of code. 
So there are two options to get such facility from android studio:
1.  Your code is  not minified
2. The code is part of your project and part of other library

Your log shows that this ANR is outside of your project so why you are not getting Blue Clickable Link in Log.

Take care of:
1. Post Complete setup of ANR Spy that how you have configured it.
2. Always use ANRSpyListener callback methods to print logs for better investigation

The log is not sufficient to analyze. So closing the issue

**Closed as completed** 2023-01-02 05:47 UTC
